# Generated by Django 5.1.3 on 2024-12-09 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('S', 'Sport'), ('C', 'Cinema'), ('F', 'Fashion')], max_length=2)),
                ('name', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
